### PR TITLE
Task UI revamp & Massive refactor

### PR DESCRIPTION
**Pull request by charlescohanlon**
Massive refactor and UI revamp. Still TODO: extract all common code from folder.jsx and home.jsx

### CODE REVIEW

**Comment by charlescohanlon** [comment]
another TODO: add more code comments/documentation

**Review by arnavbhola123 — APPROVED** [review]
LGTM

**Review by kct417 — APPROVED** [review]
lgtm

**Comment by charlescohanlon** [comment]
Didn't need pushed directly instead

**Pull request closed without merging**
