### PR TITLE
Mongoose testing and coverage

### LINKED ISSUE #55: Mongoose Testing
- testing user model
- testing user services
- 100% code coverage of these two files

### PR DESCRIPTION
**Pull request by kct417**

### CODE REVIEW

**Comment by kct417** [comment]
This pr should probably be merged before the other prs.

**Comment by arnavbhola123** [comment]
LGTM

**Review by charlescohanlon — APPROVED** [review]
looksa good to me a mario

**Comment by ishaansathaye** [comment]
LGTM

**Review by ishaansathaye — APPROVED** [review]
sweet. lgtm.

**Pull request merged**
