### PR TITLE
Refactor

### LINKED ISSUE #38: Finish Login/Register Page UI's
- Change login page UI to match website's theme
- Maybe use a MUI component if easier

### PR DESCRIPTION
**Pull request by charlescohanlon**
- Refactor login and register pages
- Overhaul banner alert system
- Use banner alert system every where UI interacts with user (no more alert())

### CODE REVIEW

**Comment by charlescohanlon** [comment]
Note: I also removed the "Prompt AI" stuff from the frontend as we decided we wouldn't have time for that.

**Review by kct417 — APPROVED** [review]
LGTM!

**Review by arnavbhola123 — APPROVED** [review]
LGTM

**Review by jlowe11 — APPROVED** [review]
LGTM

**Review by ishaansathaye — APPROVED** [review]
sweet. lgtm.

**Pull request merged**
