### PR TITLE
Added dropdowns for adding folders and dividers when adding new task

### PR DESCRIPTION
**Pull request by arnavbhola123**

### CODE REVIEW

**Review by ishaansathaye — APPROVED** [review]
Creative way to add a dropdown! LGTM!

**Review by kct417 — APPROVED** [review]
LGTM!

**Review by jlowe11 — APPROVED** [review]
LGTM!

**Review by ravippanchal — APPROVED** [review]

**Review by charlescohanlon — APPROVED** [review]
Constants like API_PREFIX and INVALID_TOKEN should probably be imported from a dedicated file or something (like .env) and not passed as props because it adds unnecessary clutter.

**Pull request merged**
