### PR TITLE
Plus button UI for menu overlay

### PR DESCRIPTION
**Pull request by ravippanchal**
This is the menu popup overlay when the plus button is pressed. It also contains the overlays of the "Add tasks", "Add folders" ...etc. if pressed with user text inputs.

### CODE REVIEW

**Review by ishaansathaye — COMMENTED** [review]
lgtm

**Comment by ishaansathaye** [comment]
also i can merge this into the sidebar when it gets 1 more review

**Review by kct417 — APPROVED** [review]
Will need to revise to use bootstrap.
Other than that LGTM

**Comment by kct417** [comment]
@ishaansathaye you need to review it not just comment.

**Comment by ishaansathaye** [comment]
> @ishaansathaye you need to review it not just comment.

I did review it

**Comment by ishaansathaye** [comment]
> @ishaansathaye you need to review it not just comment.

I thought I did review it. I will do it again

**Review by ishaansathaye — APPROVED** [review]

**Pull request merged**
